### ISSUE TITLE
confirm post 요청시 400 에러 발생

### ISSUE THREAD

**Issue by su-ram** [M-U-I-N-D-O/muindo-server#17]

**Comment by Sung-Heon** [comment]
스웨거의 예시값에 해당하는 look이 db에 없어서 생기는 에러였음.

**Comment by Sung-Heon** [comment]
1. 게스트일때는 발생하고, 이메일 로그인등 하면 발생안하던 이슈
2. 게스트쪽 토큰발행을 unique id로 하던것을 user.id로 바꿈
3. 해결
